resource_group_name = "DansApp"
app_service_plan_name = "myhealth-asp"
container_image_name = "myhealth/fhir.proxy:latest"
container_registry_name = "myhealthregistry"
authentication_authority = "https://myhealth-identity-sts.azurewebsites.net"
authentication_audience = "fhir-api"