resource_group_name = "DansApp"
app_service_plan_name = "myhealth-asp"
container_image_name = "myhealth/identity.api:latest"
container_registry_name = "myhealthregistry"
application_insights_name = "myhealth-insights"