resource_group_name = "DansApp"
app_service_plan_name = "myhealth-asp"
container_image_name = "myhealth/healthrecord.api:latest"
container_registry_name = "myhealthregistry"
application_insights_name = "myhealth-insights"
authentication_authority = "https://myhealth-identity-sts.azurewebsites.net"
authentication_audience = "myhealth-healthrecord-api"
fhir_server_base_address = "https://myhealth-fhir.azurewebsites.net"
