resource_group_name = "DansApp"
app_service_plan_name = "myhealth-asp"
container_image_name = "myhealth/observations.api:latest"
container_registry_name = "myhealthregistry"
application_insights_name = "myhealth-insights"
authentication_authority = "https://myhealth-identity-api.azurewebsites.net"
authentication_audience = "observations-api"